GET http://localhost:3001/servico


###
POST http://localhost:3001/usuario/login
Content-Type: application/json

{
    "email": "m@mail.com",
    "senha": "#Senha123"
}

###
POST http://localhost:3001/usuario/registrar
Content-Type: application/json

{
    "nome": "Maria Ester",
    "email": "m@mail.com",
    "senha": "#Senha123",
    "telefone": "11999999999"
}

###
POST http://localhost:3001/agendamentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6Ik1hcmlhIEVzdGVyIiwiZW1haWwiOiJtQG1haWwuY29tIiwidGVsZWZvbmUiOiIxMTk5OTk5OTk5OSIsImJhcmJlaXJvIjpmYWxzZSwiaWF0IjoxNzI0MzcxOTgwLCJleHAiOjE3MjU2Njc5ODB9.cBMaXcvYL9oev5QwrMrmqC-Tn1DqcIOFGNBSQ1Jam4I
Content-Type: application/json

{
    "data": "2024-10-30T13:00:00.000Z",
    "usuario": { "id": 2 },
    "profissional": { "id": 4 },
    "servicos": [
        { "id": 1 }, 
        { "id": 2 },
        { "id": 3 }
    ]
}

###
GET http://localhost:3001/agendamentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6Ik1hcmlhIEVzdGVyIiwiZW1haWwiOiJtQG1haWwuY29tIiwidGVsZWZvbmUiOiIxMTk5OTk5OTk5OSIsImJhcmJlaXJvIjpmYWxzZSwiaWF0IjoxNzI0MzcxOTgwLCJleHAiOjE3MjU2Njc5ODB9.cBMaXcvYL9oev5QwrMrmqC-Tn1DqcIOFGNBSQ1Jam4I

###
GET http://localhost:3001/agendamentos/4/2024-10-30 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6Ik1hcmlhIEVzdGVyIiwiZW1haWwiOiJtQG1haWwuY29tIiwidGVsZWZvbmUiOiIxMTk5OTk5OTk5OSIsImJhcmJlaXJvIjpmYWxzZSwiaWF0IjoxNzI0MzcxOTgwLCJleHAiOjE3MjU2Njc5ODB9.cBMaXcvYL9oev5QwrMrmqC-Tn1DqcIOFGNBSQ1Jam4I

###
DELETE http://localhost:3001/agendamentos/1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6Ik1hcmlhIEVzdGVyIiwiZW1haWwiOiJtQG1haWwuY29tIiwidGVsZWZvbmUiOiIxMTk5OTk5OTk5OSIsImJhcmJlaXJvIjpmYWxzZSwiaWF0IjoxNzI0MzcxOTgwLCJleHAiOjE3MjU2Njc5ODB9.cBMaXcvYL9oev5QwrMrmqC-Tn1DqcIOFGNBSQ1Jam4I

###
GET http://localhost:3001/profissionais

###
GET http://localhost:3001/servicos